### ISSUE TITLE
Vagrant setup out of date?

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/verboice#675]
As of 590ee08012d1cb16e6506b6c018d6cb0d0d71700, running `vagrant up` in Verboice gives an error while binding with ZeroMQ while accessing the web:

```
Function 'zmq_ctx_new' not found in [libzmq.so] (FFI::NotFoundError)
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/ffi-1.9.6/lib/ffi/library.rb:261:in `attach_function'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/ffi-rzmq-core-1.0.3/lib/ffi-rzmq-core/libzmq.rb:76:in `<module:LibZMQ>'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/ffi-rzmq-core-1.0.3/lib/ffi-rzmq-core/libzmq.rb:6:in `<top (required)>'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `block in require'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:236:in `load_dependency'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/ffi-rzmq-core-1.0.3/lib/ffi-rzmq-core.rb:3:in `<top (required)>'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `block in require'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:236:in `load_dependency'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/ffi-rzmq-2.0.1/lib/ffi-rzmq.rb:66:in `<top (required)>'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `block in require'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:236:in `load_dependency'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/bundler/gems/poirot_rails-22bbb52ca0fb/lib/poirot_rails/zmq_device.rb:1:in `<top (required)>'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `block in require'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:236:in `load_dependency'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/bundler/gems/poirot_rails-22bbb52ca0fb/lib/poirot_rails.rb:8:in `<top (required)>'
  /var/lib/gems/1.9.1/gems/bundler-1.8.3/lib/bundler/runtime.rb:76:in `require'
  /var/lib/gems/1.9.1/gems/bundler-1.8.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  /var/lib/gems/1.9.1/gems/bundler-1.8.3/lib/bundler/runtime.rb:72:in `each'
  /var/lib/gems/1.9.1/gems/bundler-1.8.3/lib/bundler/runtime.rb:72:in `block in require'
  /var/lib/gems/1.9.1/gems/bundler-1.8.3/lib/bundler/runtime.rb:61:in `each'
  /var/lib/gems/1.9.1/gems/bundler-1.8.3/lib/bundler/runtime.rb:61:in `require'
  /var/lib/gems/1.9.1/gems/bundler-1.8.3/lib/bundler.rb:134:in `require'
  /home/vagrant/verboice/config/application.rb:29:in `<top (required)>'
  /home/vagrant/verboice/config/environment.rb:19:in `require'
  /home/vagrant/verboice/config/environment.rb:19:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
  /home/vagrant/verboice/.bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.59/helper-scripts/rack-loader.rb:108:in `eval'
  /var/lib/gems/1.9.1/gems/passenger-4.0.59/helper-scripts/rack-loader.rb:108:in `load_app'
  /var/lib/gems/1.9.1/gems/passenger-4.0.59/helper-scripts/rack-loader.rb:127:in `<module:App>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.59/helper-scripts/rack-loader.rb:27:in `<module:PhusionPassenger>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.59/helper-scripts/rack-loader.rb:26:in `<main>'
```

Here's the full page text: https://gist.github.com/matiasgarciaisaia/76502e282c3b5d762534

Am I doing something wrong? Is there anything missing?

**Comment by achintangal** [comment]
I am facing the same problem too. In my case, I am installing verboice on my own server. How can I fix it?

**Comment by matiasgarciaisaia** [comment]
Hi @achintangal!

I don't have a solution to this yet - haven't tried -, but you can get the `.travis.yml` file as a base to know which packages have to be updated in the `Vagrantfile`. This error talks specifically about `libzqm-dev`, which in the `.travis.yml` is replaced by `libzmq3-dev`.

If you get to a solution, it would be great to have a pull request with the fix :)

**Comment by achintangal** [comment]
It looks like ubuntu doesn't come with the latest zeromq (3.0?) Adding a repository seems to do the trick. But it looks like you already made the fix :)

**Comment by matiasgarciaisaia** [comment]
@achintangal: if you could try the PR #687 and confirm if it works OK, that would be great - so we can merge it to master.

**Comment by achintangal** [comment]
@matiasgarciaisaia Sounds good. I will test it over the weekend.

**Comment by achintangal** [comment]
@matiasgarciaisaia I did a vagrant up after checkingout your branch. Everything seems to be working. Let me know if there are any other tests I have to run.

**Comment by spalladino** [comment]
Closing this issue. Vagrantfile is now up-to-date for the upcoming 2.8 (or 3.0) release
