### ISSUE TITLE
ActionDispatch::Cookies::CookieOverflow while importing a call flow

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/verboice#677]
Running Verboice locally (on the `local.instedd.org` domain), with the cookies just cleared, I log into the application (using Guisso), and when I import a call flow (exported from production) Verboice fails with the following error.

It seems there's an exception, and it's trying to be set for the `flash:` error - as a cookie -, and as that fails, user gets this CookieOverflow error (@ggiraldez dixit).

```
ActionDispatch::Cookies::CookieOverflow (ActionDispatch::Cookies::CookieOverflow):
  actionpack (3.2.18) lib/action_dispatch/middleware/cookies.rb:305:in `[]='
  actionpack (3.2.18) lib/action_dispatch/middleware/session/cookie_store.rb:64:in `set_cookie'
  rack (1.4.5) lib/rack/session/abstract/id.rb:335:in `commit_session'
  rack (1.4.5) lib/rack/session/abstract/id.rb:211:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.18) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.18) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.18) lib/active_support/callbacks.rb:405:in `_run__3454857530308550410__call__2178465786449310277__callbacks'
  activesupport (3.2.18) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.18) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.18) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.18) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  /Users/mgarcia/.rvm/gems/ruby-1.9.3-p550@verboice/bundler/gems/poirot_rails-22bbb52ca0fb/lib/poirot_rails/middleware.rb:44:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.18) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.18) lib/rails/rack/logger.rb:18:in `call'
  /Users/mgarcia/.rvm/gems/ruby-1.9.3-p550@verboice/bundler/gems/poirot_rails-22bbb52ca0fb/lib/poirot_rails/middleware.rb:24:in `block in call'
  /Users/mgarcia/.rvm/gems/ruby-1.9.3-p550@verboice/bundler/gems/poirot_rails-22bbb52ca0fb/lib/poirot_rails/activity.rb:29:in `start_from'
  /Users/mgarcia/.rvm/gems/ruby-1.9.3-p550@verboice/bundler/gems/poirot_rails-22bbb52ca0fb/lib/poirot_rails/middleware.rb:23:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.18) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.18) lib/action_dispatch/middleware/static.rb:63:in `call'
  railties (3.2.18) lib/rails/engine.rb:484:in `call'
  railties (3.2.18) lib/rails/application.rb:231:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.18) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /Users/mgarcia/.rvm/rubies/ruby-1.9.3-p550/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  /Users/mgarcia/.rvm/rubies/ruby-1.9.3-p550/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /Users/mgarcia/.rvm/rubies/ruby-1.9.3-p550/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

This is the full log: https://gist.github.com/matiasgarciaisaia/c2d4e1bc8fdb0564c1e0

**Comment by matiasgarciaisaia** [comment]
:+1: Works for me!
